services:
  database:
    image: shawntrznadel/hack-me-silly-postgres-db
    ports:
      - 5432:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
  server:
    image: shawntrznadel/hack-me-silly-server
    ports:
      - 3001:3001
    extra_hosts:
      - "host.docker.internal:host-gateway"
  app:
    image: shawntrznadel/hack-me-silly
    ports:
     - 3000:80